<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <BlazorDisableThrowNavigationException>true</BlazorDisableThrowNavigationException>
  </PropertyGroup>

  <ItemGroup>
    <Compile Remove="wwwroot\lib\ImgPizza\**" />
    <Content Remove="wwwroot\lib\ImgPizza\**" />
    <EmbeddedResource Remove="wwwroot\lib\ImgPizza\**" />
    <None Remove="wwwroot\lib\ImgPizza\**" />
  </ItemGroup>

  <ItemGroup>
    <Folder Include="Infrastructure\" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\BlazorApp_Formation_Pizza_Model_DTO\BlazorApp_Formation_Pizza_Model_DTO.csproj" />
  </ItemGroup>

</Project>
